### ISSUE TITLE
Example for proc macro

### ISSUE THREAD

**Issue by hellow554** [LukasKalbertodt/litrs#3]
Your readme states:

> This is particularly useful for proc macros

but yet there's no example for a proc macro.
I can understand that it would be overkill for the readme, but consider creating an examples directory and put it there for a full-fledged example.

**Comment by LukasKalbertodt** [comment]
Very good point! Thanks for reporting.

I just pushed some commits that add a proc-macro example to the README and also a full example in the `examples/` directory. I guess this should be sufficient for now?

**Comment by hellow554** [comment]
Amazing! Thank you Lukas.
